### ISSUE TITLE
small white square dialog that's unmoveable shows up on OS X with 1.12.1 after waking from sleep

### ISSUE THREAD

**Issue by raydawg** [nightingale-media-player/nightingale-hacking#353] opened 2015-07-21 19:42 UTC
A small white square window/dialogbox that's unmoveable shows up on OS X with 1.12.1 build 2454.

Tried it on two different OS X laptops, is reproducible.

It seems to happen after the macbook is put to sleep and then awakened.  

The square window is totally white, no decorators, seems to be square, maybe 128x128, always shows up in the same location, cannot be hidden, moved.  Cannot be closed/minimized/dismissed, doesn't respond to keystrokes such as ESC, ENTER, SPACE, Command-W.

Clicking on it hides all the menus in the menu bar on OS X except for apple and Nightingale.

It's likely not a window as using the hot corner feature in OS X to show all the windows for the app makes the white square go away, showing the main window.  So likely a floating widget of some kind like a dialog box.

Does not affect anything else.  Playback, etc. still work.  But it's very annoying.

Thanks.

![image](https://cloud.githubusercontent.com/assets/6388477/8810709/f0c1f0c8-2fbe-11e5-9d20-8d0beb2d59dc.png)

![image](https://cloud.githubusercontent.com/assets/6388477/8810733/17657fce-2fbf-11e5-96ba-4c7cdb8659c8.png)

**Comment by freaktechnik** [comment] 2015-07-21 20:17
Closing as duplicate of #347

**Closed as completed by freaktechnik** 2015-07-21 20:17 UTC
Labels: Mac OS X, Duplicate
