### ISSUE TITLE
Default Feather Skinning Over Title Bar on Mac OS X 10.8 (Mountain Lion)

### ISSUE THREAD

**Issue by zjays** [nightingale-media-player/nightingale-hacking#349] opened 2015-05-14 22:42 UTC
The default bluemonday feather appears to skin over the title bar on Mac OS X 10.8 (Mountain Lion). This issue does not occur on OS X 10.6 or 10.7.

OS X 10.7:
![nightingale screenshot mac os x 10 7](https://cloud.githubusercontent.com/assets/3302572/7643570/928503d2-fa68-11e4-8aae-202cbfdc8c30.png)

OS X 10.8:
![nightingale screenshot mac os x 10 8](https://cloud.githubusercontent.com/assets/3302572/7643571/92b0366a-fa68-11e4-8e6d-454c33bc48d2.png)

**Comment by freaktechnik** [comment] 2015-05-14 23:07
Duplicate of #107

**Closed as completed by freaktechnik** 2015-05-14 23:07 UTC
Labels: UI, Mac OS X, Duplicate
